<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Teste P21 | ') ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->appendStylesheet($this->basePath('frontend/vendors/bootstrap/dist/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/font-awesome/css/font-awesome.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/nprogress/nprogress.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/iCheck/skins/flat/green.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/jqvmap/dist/jqvmap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/bootstrap-daterangepicker/daterangepicker.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->appendStylesheet($this->basePath('frontend/build/css/custom.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="clearfix"></div>
                <br/>
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-user"></i> Torcedores <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="<?= $this->url('listar'); ?>">Lista de Torcedores</a></li>
                                    <li><a href="<?= $this->url('home'); ?>">Importar Torcedores</a></li>
                                </ul>
                                <ul class="nav child_menu">

                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <img src="img/img.jpg" alt="">John Doe
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="javascript:;"> Profile</a></li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="badge bg-red pull-right">50%</span>
                                        <span>Settings</span>
                                    </a>
                                </li>
                                <li><a href="javascript:;">Help</a></li>
                                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                            </ul>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                               aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                                <span class="badge bg-green">6</span>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <a>
                                        <span class="image"><img src="img/img.jpg" alt="Profile Image"/></span>
                                        <span>
                                        <span>John Smith</span>
                                        <span class="time">3 mins ago</span>
                                        </span>
                                        <span class="message">
Film festivals used to be do-or-die moments for movie makers. They were where...
</span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="img/img.jpg" alt="Profile Image"/></span>
                                        <span>
<span>John Smith</span>
<span class="time">3 mins ago</span>
</span>
                                        <span class="message">
Film festivals used to be do-or-die moments for movie makers. They were where...
</span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="img/img.jpg" alt="Profile Image"/></span>
                                        <span>
<span>John Smith</span>
<span class="time">3 mins ago</span>
</span>
                                        <span class="message">
Film festivals used to be do-or-die moments for movie makers. They were where...
</span>
                                    </a>
                                </li>
                                <li>
                                    <a>
                                        <span class="image"><img src="img/img.jpg" alt="Profile Image"/></span>
                                        <span>
<span>John Smith</span>
<span class="time">3 mins ago</span>
</span>
                                        <span class="message">
Film festivals used to be do-or-die moments for movie makers. They were where...
</span>
                                    </a>
                                </li>
                                <li>
                                    <div class="text-center">
                                        <a>
                                            <strong>See All Alerts</strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="right_col" role="main">
            <?= $this->content ?>
        </div>


        <footer>
            <div class="pull-right">

            </div>
            <div class="clearfix"></div>
        </footer>

    </div>
</div>
<!-- Scripts -->
<?= $this->headScript()
    ->appendFile($this->basePath('frontend/vendors/jquery/dist/jquery.min.js'))
    ->appendFile($this->basePath('frontend/vendors/bootstrap/dist/js/bootstrap.min.js'))
    ->appendFile($this->basePath('frontend/vendors/fastclick/lib/fastclick.js'))
    ->appendFile($this->basePath('frontend/vendors/nprogress/nprogress.js'))
    ->appendFile($this->basePath('frontend/vendors/Chart.js/dist/Chart.min.js'))
    ->appendFile($this->basePath('frontend/vendors/gauge.js/dist/gauge.min.js'))
    ->appendFile($this->basePath('frontend/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js'))
    ->appendFile($this->basePath('frontend/vendors/iCheck/icheck.min.js'))
    ->appendFile($this->basePath('frontend/vendors/skycons/skycons.js'))
    ->appendFile($this->basePath('frontend/vendors/Flot/jquery.flot.js'))
    ->appendFile($this->basePath('frontend/vendors/Flot/jquery.flot.pie.js'))
    ->appendFile($this->basePath('frontend/vendors/Flot/jquery.flot.time.js'))
    ->appendFile($this->basePath('frontend/vendors/Flot/jquery.flot.stack.js'))
    ->appendFile($this->basePath('frontend/vendors/Flot/jquery.flot.resize.js'))
    ->appendFile($this->basePath('frontend/vendors/flot.orderbars/js/jquery.flot.orderBars.js'))
    ->appendFile($this->basePath('frontend/vendors/flot-spline/js/jquery.flot.spline.min.js'))
    ->appendFile($this->basePath('frontend/vendors/flot.curvedlines/curvedLines.js'))
    ->appendFile($this->basePath('frontend/vendors/DateJS/build/date.js'))
    ->appendFile($this->basePath('frontend/vendors/jqvmap/dist/jquery.vmap.js'))
    ->appendFile($this->basePath('frontend/vendors/jqvmap/dist/maps/jquery.vmap.world.js'))
    ->appendFile($this->basePath('frontend/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js'))
    ->appendFile($this->basePath('frontend/vendors/moment/min/moment.min.js'))
    ->appendFile($this->basePath('frontend/vendors/bootstrap-daterangepicker/daterangepicker.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net/js/jquery.dataTables.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-buttons/js/buttons.flash.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-buttons/js/buttons.html5.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-buttons/js/buttons.print.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
    ->appendFile($this->basePath('frontend/vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
    ->appendFile('https://cdnjs.com/libraries/jquery.mask.js')
    ->appendFile($this->basePath('frontend/build/js/custom.min.js'))
?>

<script type="a27d9048064935a0473e49e1-text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-23581568-13', 'auto');
    ga('send', 'pageview');


</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js"
        data-cf-settings="a27d9048064935a0473e49e1-|49" defer="">

</script>
<script type="text/javascript">
    $(document).ready(function()
    {
        $('.btn-excluir').on('click',function()
        {
            var id = $(this).attr('data-id');
            $('#id-excluir').val(id);
        });
    });
</script>
</body>
</html>
</html>

